<?php

/**
 * Collection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Collection extends BaseCollection
{

    public function getPath()
    {
        $parents = array();

        $item = $this->getItems()->getFirst();
        if (!$item)
            return array();
        $parents = $item->getPath();

        array_pop($parents);

        return $parents;
    }

    public function getSlug()
    {
        return Cotinga::slugify($this->name);
    }

}
