<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Item extends BaseItem
{

    protected $metadata = array();
    protected $createdMap = false;

    public function createMetadataMap()
    {
        foreach ($this->getMetadatavalues() as $mv) {

            $name = 'dc.' . $mv->Metadatafieldregistry->element;
            if ($mv->Metadatafieldregistry->qualifier != null) {
                $name .= '.' . $mv->Metadatafieldregistry->qualifier;
            }

            $this->metadata[$name][] = $mv->text_value;
        }
        $this->createdMap = true;
    }

    public function getMetadata()
    {
        if (!$this->createdMap) {
            $this->createMetadataMap();
        }
        return $this->metadata;
    }

    public function __get($name)
    {
        if ($name == 'metadata') {
            return $this->getMetadata();
        }
        return parent::__get($name);
    }

    public function getPath()
    {
        $parents = array();
        $parent = $this;

        foreach ($this->getCommunities() as $community) {
            $parents[] = array(
                'id'=>$community->community_id,
                'type'=>'community',
                'name'=>$community->name,
                'slug'=>$community->getSlug()
                );
        }

        $parents = array_reverse($parents);
        foreach ($this->getCollections() as $collection) {
            $parents[] = array(
                'id'=>$collection->collection_id,
                'type'=>'collection',
                'name'=>$collection->name,
                'slug'=>$collection->getSlug()
                );
        }

        return $parents;
    }

    

    public function getSlug()
    {
        $metadata = $this->getMetadata();
        return Cotinga::slugify($metadata['dc.title'][0]);
    }

   

}
