<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Epersongroup2workspaceitem_Item', 'doctrine');

/**
 * BasePublic_Epersongroup2workspaceitem_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $eperson_group_id
 * @property integer $workspace_item_id
 * 
 * @method integer                                getId()                Returns the current record's "id" value
 * @method integer                                getEpersonGroupId()    Returns the current record's "eperson_group_id" value
 * @method integer                                getWorkspaceItemId()   Returns the current record's "workspace_item_id" value
 * @method Public_Epersongroup2workspaceitem_Item setId()                Sets the current record's "id" value
 * @method Public_Epersongroup2workspaceitem_Item setEpersonGroupId()    Sets the current record's "eperson_group_id" value
 * @method Public_Epersongroup2workspaceitem_Item setWorkspaceItemId()   Sets the current record's "workspace_item_id" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Epersongroup2workspaceitem_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.epersongroup2workspaceitem');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eperson_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('workspace_item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}