<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_CommunityItemCount_Item', 'doctrine');

/**
 * BasePublic_CommunityItemCount_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $community_id
 * @property integer $count
 * @property Public_Community_Item $Public_Community_Item
 * 
 * @method integer                        getCommunityId()           Returns the current record's "community_id" value
 * @method integer                        getCount()                 Returns the current record's "count" value
 * @method Public_Community_Item          getPublicCommunityItem()   Returns the current record's "Public_Community_Item" value
 * @method Public_CommunityItemCount_Item setCommunityId()           Sets the current record's "community_id" value
 * @method Public_CommunityItemCount_Item setCount()                 Sets the current record's "count" value
 * @method Public_CommunityItemCount_Item setPublicCommunityItem()   Sets the current record's "Public_Community_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_CommunityItemCount_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.community_item_count');
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Community_Item', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));
    }
}