<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Item_Item', 'doctrine');

/**
 * BasePublic_Item_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property integer $submitter_id
 * @property boolean $in_archive
 * @property boolean $withdrawn
 * @property integer $owning_collection
 * @property timestamp $last_modified
 * @property Public_Eperson_Item $Public_Eperson_Item
 * @property Doctrine_Collection $Public_BiItem_Items
 * @property Doctrine_Collection $Public_HarvestedItem_Items
 * @property Doctrine_Collection $Public_BiWithdrawn_Items
 * @property Doctrine_Collection $Public_Bi2Dmap_Items
 * @property Doctrine_Collection $Public_Collection_Items
 * @property Doctrine_Collection $Public_Item2bundle_Items
 * @property Doctrine_Collection $Public_Collection2item_Items
 * @property Doctrine_Collection $Public_Metadatavalue_Items
 * @property Doctrine_Collection $Public_Bi4Dmap_Items
 * @property Doctrine_Collection $Public_Workflowitem_Items
 * @property Doctrine_Collection $Public_Communities2item_Items
 * @property Doctrine_Collection $Public_Workspaceitem_Items
 * 
 * @method integer             getItemId()                        Returns the current record's "item_id" value
 * @method integer             getSubmitterId()                   Returns the current record's "submitter_id" value
 * @method boolean             getInArchive()                     Returns the current record's "in_archive" value
 * @method boolean             getWithdrawn()                     Returns the current record's "withdrawn" value
 * @method integer             getOwningCollection()              Returns the current record's "owning_collection" value
 * @method timestamp           getLastModified()                  Returns the current record's "last_modified" value
 * @method Public_Eperson_Item getPublicEpersonItem()             Returns the current record's "Public_Eperson_Item" value
 * @method Doctrine_Collection getPublicBiItemItems()             Returns the current record's "Public_BiItem_Items" collection
 * @method Doctrine_Collection getPublicHarvestedItemItems()      Returns the current record's "Public_HarvestedItem_Items" collection
 * @method Doctrine_Collection getPublicBiWithdrawnItems()        Returns the current record's "Public_BiWithdrawn_Items" collection
 * @method Doctrine_Collection getPublicBi2DmapItems()            Returns the current record's "Public_Bi2Dmap_Items" collection
 * @method Doctrine_Collection getPublicCollectionItems()         Returns the current record's "Public_Collection_Items" collection
 * @method Doctrine_Collection getPublicItem2bundleItems()        Returns the current record's "Public_Item2bundle_Items" collection
 * @method Doctrine_Collection getPublicCollection2itemItems()    Returns the current record's "Public_Collection2item_Items" collection
 * @method Doctrine_Collection getPublicMetadatavalueItems()      Returns the current record's "Public_Metadatavalue_Items" collection
 * @method Doctrine_Collection getPublicBi4DmapItems()            Returns the current record's "Public_Bi4Dmap_Items" collection
 * @method Doctrine_Collection getPublicWorkflowitemItems()       Returns the current record's "Public_Workflowitem_Items" collection
 * @method Doctrine_Collection getPublicCommunities2itemItems()   Returns the current record's "Public_Communities2item_Items" collection
 * @method Doctrine_Collection getPublicWorkspaceitemItems()      Returns the current record's "Public_Workspaceitem_Items" collection
 * @method Public_Item_Item    setItemId()                        Sets the current record's "item_id" value
 * @method Public_Item_Item    setSubmitterId()                   Sets the current record's "submitter_id" value
 * @method Public_Item_Item    setInArchive()                     Sets the current record's "in_archive" value
 * @method Public_Item_Item    setWithdrawn()                     Sets the current record's "withdrawn" value
 * @method Public_Item_Item    setOwningCollection()              Sets the current record's "owning_collection" value
 * @method Public_Item_Item    setLastModified()                  Sets the current record's "last_modified" value
 * @method Public_Item_Item    setPublicEpersonItem()             Sets the current record's "Public_Eperson_Item" value
 * @method Public_Item_Item    setPublicBiItemItems()             Sets the current record's "Public_BiItem_Items" collection
 * @method Public_Item_Item    setPublicHarvestedItemItems()      Sets the current record's "Public_HarvestedItem_Items" collection
 * @method Public_Item_Item    setPublicBiWithdrawnItems()        Sets the current record's "Public_BiWithdrawn_Items" collection
 * @method Public_Item_Item    setPublicBi2DmapItems()            Sets the current record's "Public_Bi2Dmap_Items" collection
 * @method Public_Item_Item    setPublicCollectionItems()         Sets the current record's "Public_Collection_Items" collection
 * @method Public_Item_Item    setPublicItem2bundleItems()        Sets the current record's "Public_Item2bundle_Items" collection
 * @method Public_Item_Item    setPublicCollection2itemItems()    Sets the current record's "Public_Collection2item_Items" collection
 * @method Public_Item_Item    setPublicMetadatavalueItems()      Sets the current record's "Public_Metadatavalue_Items" collection
 * @method Public_Item_Item    setPublicBi4DmapItems()            Sets the current record's "Public_Bi4Dmap_Items" collection
 * @method Public_Item_Item    setPublicWorkflowitemItems()       Sets the current record's "Public_Workflowitem_Items" collection
 * @method Public_Item_Item    setPublicCommunities2itemItems()   Sets the current record's "Public_Communities2item_Items" collection
 * @method Public_Item_Item    setPublicWorkspaceitemItems()      Sets the current record's "Public_Workspaceitem_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Item_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.item');
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('submitter_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('in_archive', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('withdrawn', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('owning_collection', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('last_modified', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Eperson_Item', array(
             'local' => 'submitter_id',
             'foreign' => 'eperson_id'));

        $this->hasMany('Public_BiItem_Item as Public_BiItem_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_HarvestedItem_Item as Public_HarvestedItem_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_BiWithdrawn_Item as Public_BiWithdrawn_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Bi2Dmap_Item as Public_Bi2Dmap_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items', array(
             'local' => 'item_id',
             'foreign' => 'template_item_id'));

        $this->hasMany('Public_Item2bundle_Item as Public_Item2bundle_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Collection2item_Item as Public_Collection2item_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Metadatavalue_Item as Public_Metadatavalue_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Bi4Dmap_Item as Public_Bi4Dmap_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Workflowitem_Item as Public_Workflowitem_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Communities2item_Item as Public_Communities2item_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasMany('Public_Workspaceitem_Item as Public_Workspaceitem_Items', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));
    }
}