<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Community2community_Item', 'doctrine');

/**
 * BasePublic_Community2community_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_comm_id
 * @property integer $child_comm_id
 * @property Public_Community_Item $Public_Community_Item_ForParentComm
 * @property Public_Community_Item $Public_Community_Item_ForChildComm
 * 
 * @method integer                         getId()                                  Returns the current record's "id" value
 * @method integer                         getParentCommId()                        Returns the current record's "parent_comm_id" value
 * @method integer                         getChildCommId()                         Returns the current record's "child_comm_id" value
 * @method Public_Community_Item           getPublicCommunityItemForParentComm()    Returns the current record's "Public_Community_Item_ForParentComm" value
 * @method Public_Community_Item           getPublicCommunityItemForChildComm()     Returns the current record's "Public_Community_Item_ForChildComm" value
 * @method Public_Community2community_Item setId()                                  Sets the current record's "id" value
 * @method Public_Community2community_Item setParentCommId()                        Sets the current record's "parent_comm_id" value
 * @method Public_Community2community_Item setChildCommId()                         Sets the current record's "child_comm_id" value
 * @method Public_Community2community_Item setPublicCommunityItemForParentComm()    Sets the current record's "Public_Community_Item_ForParentComm" value
 * @method Public_Community2community_Item setPublicCommunityItemForChildComm()     Sets the current record's "Public_Community_Item_ForChildComm" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Community2community_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.community2community');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_comm_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('child_comm_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Community_Item as Public_Community_Item_ForParentComm', array(
             'local' => 'parent_comm_id',
             'foreign' => 'community_id'));

        $this->hasOne('Public_Community_Item as Public_Community_Item_ForChildComm', array(
             'local' => 'child_comm_id',
             'foreign' => 'community_id'));
    }
}