<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Fileextension_Item', 'doctrine');

/**
 * BasePublic_Fileextension_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_extension_id
 * @property integer $bitstream_format_id
 * @property string $extension
 * @property Public_Bitstreamformatregistry_Item $Public_Bitstreamformatregistry_Item
 * 
 * @method integer                             getFileExtensionId()                     Returns the current record's "file_extension_id" value
 * @method integer                             getBitstreamFormatId()                   Returns the current record's "bitstream_format_id" value
 * @method string                              getExtension()                           Returns the current record's "extension" value
 * @method Public_Bitstreamformatregistry_Item getPublicBitstreamformatregistryItem()   Returns the current record's "Public_Bitstreamformatregistry_Item" value
 * @method Public_Fileextension_Item           setFileExtensionId()                     Sets the current record's "file_extension_id" value
 * @method Public_Fileextension_Item           setBitstreamFormatId()                   Sets the current record's "bitstream_format_id" value
 * @method Public_Fileextension_Item           setExtension()                           Sets the current record's "extension" value
 * @method Public_Fileextension_Item           setPublicBitstreamformatregistryItem()   Sets the current record's "Public_Bitstreamformatregistry_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Fileextension_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.fileextension');
        $this->hasColumn('file_extension_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('bitstream_format_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('extension', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Bitstreamformatregistry_Item', array(
             'local' => 'bitstream_format_id',
             'foreign' => 'bitstream_format_id'));
    }
}