<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Tasklistitem_Item', 'doctrine');

/**
 * BasePublic_Tasklistitem_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tasklist_id
 * @property integer $eperson_id
 * @property integer $workflow_id
 * @property Public_Eperson_Item $Public_Eperson_Item
 * @property Public_Workflowitem_Item $Public_Workflowitem_Item
 * 
 * @method integer                  getTasklistId()               Returns the current record's "tasklist_id" value
 * @method integer                  getEpersonId()                Returns the current record's "eperson_id" value
 * @method integer                  getWorkflowId()               Returns the current record's "workflow_id" value
 * @method Public_Eperson_Item      getPublicEpersonItem()        Returns the current record's "Public_Eperson_Item" value
 * @method Public_Workflowitem_Item getPublicWorkflowitemItem()   Returns the current record's "Public_Workflowitem_Item" value
 * @method Public_Tasklistitem_Item setTasklistId()               Sets the current record's "tasklist_id" value
 * @method Public_Tasklistitem_Item setEpersonId()                Sets the current record's "eperson_id" value
 * @method Public_Tasklistitem_Item setWorkflowId()               Sets the current record's "workflow_id" value
 * @method Public_Tasklistitem_Item setPublicEpersonItem()        Sets the current record's "Public_Eperson_Item" value
 * @method Public_Tasklistitem_Item setPublicWorkflowitemItem()   Sets the current record's "Public_Workflowitem_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Tasklistitem_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.tasklistitem');
        $this->hasColumn('tasklist_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eperson_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('workflow_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Eperson_Item', array(
             'local' => 'eperson_id',
             'foreign' => 'eperson_id'));

        $this->hasOne('Public_Workflowitem_Item', array(
             'local' => 'workflow_id',
             'foreign' => 'workflow_id'));
    }
}