<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Community2collection_Item', 'doctrine');

/**
 * BasePublic_Community2collection_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $community_id
 * @property integer $collection_id
 * @property Public_Community_Item $Public_Community_Item
 * @property Public_Collection_Item $Public_Collection_Item_ForCollection
 * 
 * @method integer                          getId()                                   Returns the current record's "id" value
 * @method integer                          getCommunityId()                          Returns the current record's "community_id" value
 * @method integer                          getCollectionId()                         Returns the current record's "collection_id" value
 * @method Public_Community_Item            getPublicCommunityItem()                  Returns the current record's "Public_Community_Item" value
 * @method Public_Collection_Item           getPublicCollectionItemForCollection()    Returns the current record's "Public_Collection_Item_ForCollection" value
 * @method Public_Community2collection_Item setId()                                   Sets the current record's "id" value
 * @method Public_Community2collection_Item setCommunityId()                          Sets the current record's "community_id" value
 * @method Public_Community2collection_Item setCollectionId()                         Sets the current record's "collection_id" value
 * @method Public_Community2collection_Item setPublicCommunityItem()                  Sets the current record's "Public_Community_Item" value
 * @method Public_Community2collection_Item setPublicCollectionItemForCollection()    Sets the current record's "Public_Collection_Item_ForCollection" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Community2collection_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.community2collection');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Community_Item', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));

        $this->hasOne('Public_Collection_Item as Public_Collection_Item_ForCollection', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));
    }
}