<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_ChecksumResults_Item', 'doctrine');

/**
 * BasePublic_ChecksumResults_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $result_code
 * @property string $result_description
 * @property Doctrine_Collection $Public_MostRecentChecksum_Items
 * @property Doctrine_Collection $Public_ChecksumHistory_Items
 * 
 * @method string                      getResultCode()                      Returns the current record's "result_code" value
 * @method string                      getResultDescription()               Returns the current record's "result_description" value
 * @method Doctrine_Collection         getPublicMostRecentChecksumItems()   Returns the current record's "Public_MostRecentChecksum_Items" collection
 * @method Doctrine_Collection         getPublicChecksumHistoryItems()      Returns the current record's "Public_ChecksumHistory_Items" collection
 * @method Public_ChecksumResults_Item setResultCode()                      Sets the current record's "result_code" value
 * @method Public_ChecksumResults_Item setResultDescription()               Sets the current record's "result_description" value
 * @method Public_ChecksumResults_Item setPublicMostRecentChecksumItems()   Sets the current record's "Public_MostRecentChecksum_Items" collection
 * @method Public_ChecksumResults_Item setPublicChecksumHistoryItems()      Sets the current record's "Public_ChecksumHistory_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_ChecksumResults_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.checksum_results');
        $this->hasColumn('result_code', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('result_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Public_MostRecentChecksum_Item as Public_MostRecentChecksum_Items', array(
             'local' => 'result_code',
             'foreign' => 'result'));

        $this->hasMany('Public_ChecksumHistory_Item as Public_ChecksumHistory_Items', array(
             'local' => 'result_code',
             'foreign' => 'result'));
    }
}