<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Community_Item', 'doctrine');

/**
 * BasePublic_Community_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $community_id
 * @property string $name
 * @property string $short_description
 * @property string $introductory_text
 * @property integer $logo_bitstream_id
 * @property string $copyright_text
 * @property string $side_bar_text
 * @property integer $admin
 * @property Public_Bitstream_Item $Public_Bitstream_Item
 * @property Public_Epersongroup_Item $Public_Epersongroup_Item
 * @property Doctrine_Collection $Public_Community2collection_Items
 * @property Doctrine_Collection $Public_Community2community_Items_ForParentComm
 * @property Doctrine_Collection $Public_Community2community_Items_ForChildComm
 * @property Doctrine_Collection $Public_CommunityItemCount_Items
 * @property Doctrine_Collection $Public_Communities2item_Items
 * 
 * @method integer                  getCommunityId()                                    Returns the current record's "community_id" value
 * @method string                   getName()                                           Returns the current record's "name" value
 * @method string                   getShortDescription()                               Returns the current record's "short_description" value
 * @method string                   getIntroductoryText()                               Returns the current record's "introductory_text" value
 * @method integer                  getLogoBitstreamId()                                Returns the current record's "logo_bitstream_id" value
 * @method string                   getCopyrightText()                                  Returns the current record's "copyright_text" value
 * @method string                   getSideBarText()                                    Returns the current record's "side_bar_text" value
 * @method integer                  getAdmin()                                          Returns the current record's "admin" value
 * @method Public_Bitstream_Item    getPublicBitstreamItem()                            Returns the current record's "Public_Bitstream_Item" value
 * @method Public_Epersongroup_Item getPublicEpersongroupItem()                         Returns the current record's "Public_Epersongroup_Item" value
 * @method Doctrine_Collection      getPublicCommunity2collectionItems()                Returns the current record's "Public_Community2collection_Items" collection
 * @method Doctrine_Collection      getPublicCommunity2communityItemsForParentComm()    Returns the current record's "Public_Community2community_Items_ForParentComm" collection
 * @method Doctrine_Collection      getPublicCommunity2communityItemsForChildComm()     Returns the current record's "Public_Community2community_Items_ForChildComm" collection
 * @method Doctrine_Collection      getPublicCommunityItemCountItems()                  Returns the current record's "Public_CommunityItemCount_Items" collection
 * @method Doctrine_Collection      getPublicCommunities2itemItems()                    Returns the current record's "Public_Communities2item_Items" collection
 * @method Public_Community_Item    setCommunityId()                                    Sets the current record's "community_id" value
 * @method Public_Community_Item    setName()                                           Sets the current record's "name" value
 * @method Public_Community_Item    setShortDescription()                               Sets the current record's "short_description" value
 * @method Public_Community_Item    setIntroductoryText()                               Sets the current record's "introductory_text" value
 * @method Public_Community_Item    setLogoBitstreamId()                                Sets the current record's "logo_bitstream_id" value
 * @method Public_Community_Item    setCopyrightText()                                  Sets the current record's "copyright_text" value
 * @method Public_Community_Item    setSideBarText()                                    Sets the current record's "side_bar_text" value
 * @method Public_Community_Item    setAdmin()                                          Sets the current record's "admin" value
 * @method Public_Community_Item    setPublicBitstreamItem()                            Sets the current record's "Public_Bitstream_Item" value
 * @method Public_Community_Item    setPublicEpersongroupItem()                         Sets the current record's "Public_Epersongroup_Item" value
 * @method Public_Community_Item    setPublicCommunity2collectionItems()                Sets the current record's "Public_Community2collection_Items" collection
 * @method Public_Community_Item    setPublicCommunity2communityItemsForParentComm()    Sets the current record's "Public_Community2community_Items_ForParentComm" collection
 * @method Public_Community_Item    setPublicCommunity2communityItemsForChildComm()     Sets the current record's "Public_Community2community_Items_ForChildComm" collection
 * @method Public_Community_Item    setPublicCommunityItemCountItems()                  Sets the current record's "Public_CommunityItemCount_Items" collection
 * @method Public_Community_Item    setPublicCommunities2itemItems()                    Sets the current record's "Public_Communities2item_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Community_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.community');
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('short_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('introductory_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('logo_bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('copyright_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('side_bar_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('admin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Bitstream_Item', array(
             'local' => 'logo_bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasOne('Public_Epersongroup_Item', array(
             'local' => 'admin',
             'foreign' => 'eperson_group_id'));

        $this->hasMany('Public_Community2collection_Item as Public_Community2collection_Items', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));

        $this->hasMany('Public_Community2community_Item as Public_Community2community_Items_ForParentComm', array(
             'local' => 'community_id',
             'foreign' => 'parent_comm_id'));

        $this->hasMany('Public_Community2community_Item as Public_Community2community_Items_ForChildComm', array(
             'local' => 'community_id',
             'foreign' => 'child_comm_id'));

        $this->hasMany('Public_CommunityItemCount_Item as Public_CommunityItemCount_Items', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));

        $this->hasMany('Public_Communities2item_Item as Public_Communities2item_Items', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));
    }
}