<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Workspaceitem_Item', 'doctrine');

/**
 * BasePublic_Workspaceitem_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workspace_item_id
 * @property integer $item_id
 * @property integer $collection_id
 * @property boolean $multiple_titles
 * @property boolean $published_before
 * @property boolean $multiple_files
 * @property integer $stage_reached
 * @property integer $page_reached
 * @property Public_Item_Item $Public_Item_Item
 * @property Public_Collection_Item $Public_Collection_Item
 * 
 * @method integer                   getWorkspaceItemId()        Returns the current record's "workspace_item_id" value
 * @method integer                   getItemId()                 Returns the current record's "item_id" value
 * @method integer                   getCollectionId()           Returns the current record's "collection_id" value
 * @method boolean                   getMultipleTitles()         Returns the current record's "multiple_titles" value
 * @method boolean                   getPublishedBefore()        Returns the current record's "published_before" value
 * @method boolean                   getMultipleFiles()          Returns the current record's "multiple_files" value
 * @method integer                   getStageReached()           Returns the current record's "stage_reached" value
 * @method integer                   getPageReached()            Returns the current record's "page_reached" value
 * @method Public_Item_Item          getPublicItemItem()         Returns the current record's "Public_Item_Item" value
 * @method Public_Collection_Item    getPublicCollectionItem()   Returns the current record's "Public_Collection_Item" value
 * @method Public_Workspaceitem_Item setWorkspaceItemId()        Sets the current record's "workspace_item_id" value
 * @method Public_Workspaceitem_Item setItemId()                 Sets the current record's "item_id" value
 * @method Public_Workspaceitem_Item setCollectionId()           Sets the current record's "collection_id" value
 * @method Public_Workspaceitem_Item setMultipleTitles()         Sets the current record's "multiple_titles" value
 * @method Public_Workspaceitem_Item setPublishedBefore()        Sets the current record's "published_before" value
 * @method Public_Workspaceitem_Item setMultipleFiles()          Sets the current record's "multiple_files" value
 * @method Public_Workspaceitem_Item setStageReached()           Sets the current record's "stage_reached" value
 * @method Public_Workspaceitem_Item setPageReached()            Sets the current record's "page_reached" value
 * @method Public_Workspaceitem_Item setPublicItemItem()         Sets the current record's "Public_Item_Item" value
 * @method Public_Workspaceitem_Item setPublicCollectionItem()   Sets the current record's "Public_Collection_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Workspaceitem_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.workspaceitem');
        $this->hasColumn('workspace_item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('multiple_titles', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('published_before', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('multiple_files', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('stage_reached', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('page_reached', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Item_Item', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasOne('Public_Collection_Item', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));
    }
}