<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Epersongroup2eperson_Item', 'doctrine');

/**
 * BasePublic_Epersongroup2eperson_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $eperson_group_id
 * @property integer $eperson_id
 * @property Public_Epersongroup_Item $Public_Epersongroup_Item
 * @property Public_Eperson_Item $Public_Eperson_Item
 * 
 * @method integer                          getId()                       Returns the current record's "id" value
 * @method integer                          getEpersonGroupId()           Returns the current record's "eperson_group_id" value
 * @method integer                          getEpersonId()                Returns the current record's "eperson_id" value
 * @method Public_Epersongroup_Item         getPublicEpersongroupItem()   Returns the current record's "Public_Epersongroup_Item" value
 * @method Public_Eperson_Item              getPublicEpersonItem()        Returns the current record's "Public_Eperson_Item" value
 * @method Public_Epersongroup2eperson_Item setId()                       Sets the current record's "id" value
 * @method Public_Epersongroup2eperson_Item setEpersonGroupId()           Sets the current record's "eperson_group_id" value
 * @method Public_Epersongroup2eperson_Item setEpersonId()                Sets the current record's "eperson_id" value
 * @method Public_Epersongroup2eperson_Item setPublicEpersongroupItem()   Sets the current record's "Public_Epersongroup_Item" value
 * @method Public_Epersongroup2eperson_Item setPublicEpersonItem()        Sets the current record's "Public_Eperson_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Epersongroup2eperson_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.epersongroup2eperson');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eperson_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eperson_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Epersongroup_Item', array(
             'local' => 'eperson_group_id',
             'foreign' => 'eperson_group_id'));

        $this->hasOne('Public_Eperson_Item', array(
             'local' => 'eperson_id',
             'foreign' => 'eperson_id'));
    }
}