<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Bundle_Item', 'doctrine');

/**
 * BasePublic_Bundle_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bundle_id
 * @property string $name
 * @property integer $primary_bitstream_id
 * @property Public_Bitstream_Item $Public_Bitstream_Item
 * @property Doctrine_Collection $Public_Bundle2bitstream_Items
 * @property Doctrine_Collection $Public_Item2bundle_Items
 * 
 * @method integer               getBundleId()                      Returns the current record's "bundle_id" value
 * @method string                getName()                          Returns the current record's "name" value
 * @method integer               getPrimaryBitstreamId()            Returns the current record's "primary_bitstream_id" value
 * @method Public_Bitstream_Item getPublicBitstreamItem()           Returns the current record's "Public_Bitstream_Item" value
 * @method Doctrine_Collection   getPublicBundle2bitstreamItems()   Returns the current record's "Public_Bundle2bitstream_Items" collection
 * @method Doctrine_Collection   getPublicItem2bundleItems()        Returns the current record's "Public_Item2bundle_Items" collection
 * @method Public_Bundle_Item    setBundleId()                      Sets the current record's "bundle_id" value
 * @method Public_Bundle_Item    setName()                          Sets the current record's "name" value
 * @method Public_Bundle_Item    setPrimaryBitstreamId()            Sets the current record's "primary_bitstream_id" value
 * @method Public_Bundle_Item    setPublicBitstreamItem()           Sets the current record's "Public_Bitstream_Item" value
 * @method Public_Bundle_Item    setPublicBundle2bitstreamItems()   Sets the current record's "Public_Bundle2bitstream_Items" collection
 * @method Public_Bundle_Item    setPublicItem2bundleItems()        Sets the current record's "Public_Item2bundle_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Bundle_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bundle');
        $this->hasColumn('bundle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('primary_bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Bitstream_Item', array(
             'local' => 'primary_bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasMany('Public_Bundle2bitstream_Item as Public_Bundle2bitstream_Items', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));

        $this->hasMany('Public_Item2bundle_Item as Public_Item2bundle_Items', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));
    }
}