<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Epersongroup_Item', 'doctrine');

/**
 * BasePublic_Epersongroup_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eperson_group_id
 * @property string $name
 * @property Doctrine_Collection $Public_Group2group_Items_ForChild
 * @property Doctrine_Collection $Public_Group2group_Items_ForParent
 * @property Doctrine_Collection $Public_Collection_Items_ForWorkflowStep1
 * @property Doctrine_Collection $Public_Collection_Items_ForWorkflowStep2
 * @property Doctrine_Collection $Public_Collection_Items_ForWorkflowStep3
 * @property Doctrine_Collection $Public_Collection_Items_ForAdmin
 * @property Doctrine_Collection $Public_Collection_Items_ForSubmitter
 * @property Doctrine_Collection $Public_Resourcepolicy_Items
 * @property Doctrine_Collection $Public_Group2groupcache_Items_ForChild
 * @property Doctrine_Collection $Public_Group2groupcache_Items_ForParent
 * @property Doctrine_Collection $Public_Community_Items
 * @property Doctrine_Collection $Public_Epersongroup2eperson_Items
 * 
 * @method integer                  getEpersonGroupId()                           Returns the current record's "eperson_group_id" value
 * @method string                   getName()                                     Returns the current record's "name" value
 * @method Doctrine_Collection      getPublicGroup2groupItemsForChild()           Returns the current record's "Public_Group2group_Items_ForChild" collection
 * @method Doctrine_Collection      getPublicGroup2groupItemsForParent()          Returns the current record's "Public_Group2group_Items_ForParent" collection
 * @method Doctrine_Collection      getPublicCollectionItemsForWorkflowStep1()    Returns the current record's "Public_Collection_Items_ForWorkflowStep1" collection
 * @method Doctrine_Collection      getPublicCollectionItemsForWorkflowStep2()    Returns the current record's "Public_Collection_Items_ForWorkflowStep2" collection
 * @method Doctrine_Collection      getPublicCollectionItemsForWorkflowStep3()    Returns the current record's "Public_Collection_Items_ForWorkflowStep3" collection
 * @method Doctrine_Collection      getPublicCollectionItemsForAdmin()            Returns the current record's "Public_Collection_Items_ForAdmin" collection
 * @method Doctrine_Collection      getPublicCollectionItemsForSubmitter()        Returns the current record's "Public_Collection_Items_ForSubmitter" collection
 * @method Doctrine_Collection      getPublicResourcepolicyItems()                Returns the current record's "Public_Resourcepolicy_Items" collection
 * @method Doctrine_Collection      getPublicGroup2groupcacheItemsForChild()      Returns the current record's "Public_Group2groupcache_Items_ForChild" collection
 * @method Doctrine_Collection      getPublicGroup2groupcacheItemsForParent()     Returns the current record's "Public_Group2groupcache_Items_ForParent" collection
 * @method Doctrine_Collection      getPublicCommunityItems()                     Returns the current record's "Public_Community_Items" collection
 * @method Doctrine_Collection      getPublicEpersongroup2epersonItems()          Returns the current record's "Public_Epersongroup2eperson_Items" collection
 * @method Public_Epersongroup_Item setEpersonGroupId()                           Sets the current record's "eperson_group_id" value
 * @method Public_Epersongroup_Item setName()                                     Sets the current record's "name" value
 * @method Public_Epersongroup_Item setPublicGroup2groupItemsForChild()           Sets the current record's "Public_Group2group_Items_ForChild" collection
 * @method Public_Epersongroup_Item setPublicGroup2groupItemsForParent()          Sets the current record's "Public_Group2group_Items_ForParent" collection
 * @method Public_Epersongroup_Item setPublicCollectionItemsForWorkflowStep1()    Sets the current record's "Public_Collection_Items_ForWorkflowStep1" collection
 * @method Public_Epersongroup_Item setPublicCollectionItemsForWorkflowStep2()    Sets the current record's "Public_Collection_Items_ForWorkflowStep2" collection
 * @method Public_Epersongroup_Item setPublicCollectionItemsForWorkflowStep3()    Sets the current record's "Public_Collection_Items_ForWorkflowStep3" collection
 * @method Public_Epersongroup_Item setPublicCollectionItemsForAdmin()            Sets the current record's "Public_Collection_Items_ForAdmin" collection
 * @method Public_Epersongroup_Item setPublicCollectionItemsForSubmitter()        Sets the current record's "Public_Collection_Items_ForSubmitter" collection
 * @method Public_Epersongroup_Item setPublicResourcepolicyItems()                Sets the current record's "Public_Resourcepolicy_Items" collection
 * @method Public_Epersongroup_Item setPublicGroup2groupcacheItemsForChild()      Sets the current record's "Public_Group2groupcache_Items_ForChild" collection
 * @method Public_Epersongroup_Item setPublicGroup2groupcacheItemsForParent()     Sets the current record's "Public_Group2groupcache_Items_ForParent" collection
 * @method Public_Epersongroup_Item setPublicCommunityItems()                     Sets the current record's "Public_Community_Items" collection
 * @method Public_Epersongroup_Item setPublicEpersongroup2epersonItems()          Sets the current record's "Public_Epersongroup2eperson_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Epersongroup_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.epersongroup');
        $this->hasColumn('eperson_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Public_Group2group_Item as Public_Group2group_Items_ForChild', array(
             'local' => 'eperson_group_id',
             'foreign' => 'child_id'));

        $this->hasMany('Public_Group2group_Item as Public_Group2group_Items_ForParent', array(
             'local' => 'eperson_group_id',
             'foreign' => 'parent_id'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items_ForWorkflowStep1', array(
             'local' => 'eperson_group_id',
             'foreign' => 'workflow_step_1'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items_ForWorkflowStep2', array(
             'local' => 'eperson_group_id',
             'foreign' => 'workflow_step_2'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items_ForWorkflowStep3', array(
             'local' => 'eperson_group_id',
             'foreign' => 'workflow_step_3'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items_ForAdmin', array(
             'local' => 'eperson_group_id',
             'foreign' => 'admin'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items_ForSubmitter', array(
             'local' => 'eperson_group_id',
             'foreign' => 'submitter'));

        $this->hasMany('Public_Resourcepolicy_Item as Public_Resourcepolicy_Items', array(
             'local' => 'eperson_group_id',
             'foreign' => 'epersongroup_id'));

        $this->hasMany('Public_Group2groupcache_Item as Public_Group2groupcache_Items_ForChild', array(
             'local' => 'eperson_group_id',
             'foreign' => 'child_id'));

        $this->hasMany('Public_Group2groupcache_Item as Public_Group2groupcache_Items_ForParent', array(
             'local' => 'eperson_group_id',
             'foreign' => 'parent_id'));

        $this->hasMany('Public_Community_Item as Public_Community_Items', array(
             'local' => 'eperson_group_id',
             'foreign' => 'admin'));

        $this->hasMany('Public_Epersongroup2eperson_Item as Public_Epersongroup2eperson_Items', array(
             'local' => 'eperson_group_id',
             'foreign' => 'eperson_group_id'));
    }
}