<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Metadataschemaregistry_Item', 'doctrine');

/**
 * BasePublic_Metadataschemaregistry_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $metadata_schema_id
 * @property string $namespace
 * @property string $short_id
 * @property Doctrine_Collection $Public_Metadatafieldregistry_Items
 * 
 * @method integer                            getMetadataSchemaId()                   Returns the current record's "metadata_schema_id" value
 * @method string                             getNamespace()                          Returns the current record's "namespace" value
 * @method string                             getShortId()                            Returns the current record's "short_id" value
 * @method Doctrine_Collection                getPublicMetadatafieldregistryItems()   Returns the current record's "Public_Metadatafieldregistry_Items" collection
 * @method Public_Metadataschemaregistry_Item setMetadataSchemaId()                   Sets the current record's "metadata_schema_id" value
 * @method Public_Metadataschemaregistry_Item setNamespace()                          Sets the current record's "namespace" value
 * @method Public_Metadataschemaregistry_Item setShortId()                            Sets the current record's "short_id" value
 * @method Public_Metadataschemaregistry_Item setPublicMetadatafieldregistryItems()   Sets the current record's "Public_Metadatafieldregistry_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Metadataschemaregistry_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.metadataschemaregistry');
        $this->hasColumn('metadata_schema_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('namespace', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('short_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Public_Metadatafieldregistry_Item as Public_Metadatafieldregistry_Items', array(
             'local' => 'metadata_schema_id',
             'foreign' => 'metadata_schema_id'));
    }
}