<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Group2groupcache_Item', 'doctrine');

/**
 * BasePublic_Group2groupcache_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property integer $child_id
 * @property Public_Epersongroup_Item $Public_Epersongroup_Item_ForChild
 * @property Public_Epersongroup_Item $Public_Epersongroup_Item_ForParent
 * 
 * @method integer                      getId()                                 Returns the current record's "id" value
 * @method integer                      getParentId()                           Returns the current record's "parent_id" value
 * @method integer                      getChildId()                            Returns the current record's "child_id" value
 * @method Public_Epersongroup_Item     getPublicEpersongroupItemForChild()     Returns the current record's "Public_Epersongroup_Item_ForChild" value
 * @method Public_Epersongroup_Item     getPublicEpersongroupItemForParent()    Returns the current record's "Public_Epersongroup_Item_ForParent" value
 * @method Public_Group2groupcache_Item setId()                                 Sets the current record's "id" value
 * @method Public_Group2groupcache_Item setParentId()                           Sets the current record's "parent_id" value
 * @method Public_Group2groupcache_Item setChildId()                            Sets the current record's "child_id" value
 * @method Public_Group2groupcache_Item setPublicEpersongroupItemForChild()     Sets the current record's "Public_Epersongroup_Item_ForChild" value
 * @method Public_Group2groupcache_Item setPublicEpersongroupItemForParent()    Sets the current record's "Public_Epersongroup_Item_ForParent" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Group2groupcache_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.group2groupcache');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('child_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Epersongroup_Item as Public_Epersongroup_Item_ForChild', array(
             'local' => 'child_id',
             'foreign' => 'eperson_group_id'));

        $this->hasOne('Public_Epersongroup_Item as Public_Epersongroup_Item_ForParent', array(
             'local' => 'parent_id',
             'foreign' => 'eperson_group_id'));
    }
}