<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Bi2Dis_Item', 'doctrine');

/**
 * BasePublic_Bi2Dis_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $distinct_id
 * @property string $authority
 * @property string $value
 * @property string $sort_value
 * @property Doctrine_Collection $Public_Bi2Dmap_Items
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method integer             getDistinctId()           Returns the current record's "distinct_id" value
 * @method string              getAuthority()            Returns the current record's "authority" value
 * @method string              getValue()                Returns the current record's "value" value
 * @method string              getSortValue()            Returns the current record's "sort_value" value
 * @method Doctrine_Collection getPublicBi2DmapItems()   Returns the current record's "Public_Bi2Dmap_Items" collection
 * @method Public_Bi2Dis_Item  setId()                   Sets the current record's "id" value
 * @method Public_Bi2Dis_Item  setDistinctId()           Sets the current record's "distinct_id" value
 * @method Public_Bi2Dis_Item  setAuthority()            Sets the current record's "authority" value
 * @method Public_Bi2Dis_Item  setValue()                Sets the current record's "value" value
 * @method Public_Bi2Dis_Item  setSortValue()            Sets the current record's "sort_value" value
 * @method Public_Bi2Dis_Item  setPublicBi2DmapItems()   Sets the current record's "Public_Bi2Dmap_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Bi2Dis_Item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bi_2_dis');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('distinct_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('authority', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sort_value', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Public_Bi2Dmap_Item as Public_Bi2Dmap_Items', array(
             'local' => 'distinct_id',
             'foreign' => 'distinct_id'));
    }
}