<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BitstreamFormatRegistry', 'doctrine');

/**
 * BaseBitstreamFormatRegistry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bitstream_format_id
 * @property string $mimetype
 * @property string $short_description
 * @property string $description
 * @property integer $support_level
 * @property boolean $internal
 * @property Doctrine_Collection $FileExtensions
 * @property Doctrine_Collection $Bitstreams
 * 
 * @method integer                 getBitstreamFormatId()   Returns the current record's "bitstream_format_id" value
 * @method string                  getMimetype()            Returns the current record's "mimetype" value
 * @method string                  getShortDescription()    Returns the current record's "short_description" value
 * @method string                  getDescription()         Returns the current record's "description" value
 * @method integer                 getSupportLevel()        Returns the current record's "support_level" value
 * @method boolean                 getInternal()            Returns the current record's "internal" value
 * @method Doctrine_Collection     getFileExtensions()      Returns the current record's "FileExtensions" collection
 * @method Doctrine_Collection     getBitstreams()          Returns the current record's "Bitstreams" collection
 * @method BitstreamFormatRegistry setBitstreamFormatId()   Sets the current record's "bitstream_format_id" value
 * @method BitstreamFormatRegistry setMimetype()            Sets the current record's "mimetype" value
 * @method BitstreamFormatRegistry setShortDescription()    Sets the current record's "short_description" value
 * @method BitstreamFormatRegistry setDescription()         Sets the current record's "description" value
 * @method BitstreamFormatRegistry setSupportLevel()        Sets the current record's "support_level" value
 * @method BitstreamFormatRegistry setInternal()            Sets the current record's "internal" value
 * @method BitstreamFormatRegistry setFileExtensions()      Sets the current record's "FileExtensions" collection
 * @method BitstreamFormatRegistry setBitstreams()          Sets the current record's "Bitstreams" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBitstreamFormatRegistry extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bitstreamformatregistry');
        $this->hasColumn('bitstream_format_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('mimetype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('short_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('support_level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('internal', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FileExtension as FileExtensions', array(
             'local' => 'bitstream_format_id',
             'foreign' => 'bitstream_format_id'));

        $this->hasMany('Bitstream as Bitstreams', array(
             'local' => 'bitstream_format_id',
             'foreign' => 'bitstream_format_id'));
    }
}