<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Metadatafieldregistry', 'doctrine');

/**
 * BaseMetadatafieldregistry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $metadata_field_id
 * @property integer $metadata_schema_id
 * @property string $element
 * @property string $qualifier
 * @property string $scope_note
 * @property Metadataschemaregistry $Metadataschemaregistry
 * @property Doctrine_Collection $Metadatavalues
 * 
 * @method integer                getMetadataFieldId()        Returns the current record's "metadata_field_id" value
 * @method integer                getMetadataSchemaId()       Returns the current record's "metadata_schema_id" value
 * @method string                 getElement()                Returns the current record's "element" value
 * @method string                 getQualifier()              Returns the current record's "qualifier" value
 * @method string                 getScopeNote()              Returns the current record's "scope_note" value
 * @method Metadataschemaregistry getMetadataschemaregistry() Returns the current record's "Metadataschemaregistry" value
 * @method Doctrine_Collection    getMetadatavalues()         Returns the current record's "Metadatavalues" collection
 * @method Metadatafieldregistry  setMetadataFieldId()        Sets the current record's "metadata_field_id" value
 * @method Metadatafieldregistry  setMetadataSchemaId()       Sets the current record's "metadata_schema_id" value
 * @method Metadatafieldregistry  setElement()                Sets the current record's "element" value
 * @method Metadatafieldregistry  setQualifier()              Sets the current record's "qualifier" value
 * @method Metadatafieldregistry  setScopeNote()              Sets the current record's "scope_note" value
 * @method Metadatafieldregistry  setMetadataschemaregistry() Sets the current record's "Metadataschemaregistry" value
 * @method Metadatafieldregistry  setMetadatavalues()         Sets the current record's "Metadatavalues" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMetadatafieldregistry extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.metadatafieldregistry');
        $this->hasColumn('metadata_field_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('metadata_schema_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('element', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('qualifier', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('scope_note', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Metadataschemaregistry', array(
             'local' => 'metadata_schema_id',
             'foreign' => 'metadata_schema_id'));

        $this->hasMany('Metadatavalue as Metadatavalues', array(
             'local' => 'metadata_field_id',
             'foreign' => 'metadata_field_id'));
    }
}