<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Bitstream_Item', 'doctrine');

/**
 * BasePublic_Bitstream_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bitstream_id
 * @property integer $bitstream_format_id
 * @property string $name
 * @property string $checksum
 * @property string $checksum_algorithm
 * @property string $description
 * @property string $user_format_description
 * @property string $source
 * @property string $internal_id
 * @property boolean $deleted
 * @property integer $store_number
 * @property integer $sequence_id
 * @property integer $size_bytes
 * @property Public_Bitstreamformatregistry_Item $Public_Bitstreamformatregistry_Item
 * @property Doctrine_Collection $Public_Bundle_Items
 * @property Doctrine_Collection $Public_MostRecentChecksum_Items
 * @property Doctrine_Collection $Public_Bundle2bitstream_Items
 * @property Doctrine_Collection $Public_Collection_Items
 * @property Doctrine_Collection $Public_Community_Items
 * 
 * @method integer                             getBitstreamId()                         Returns the current record's "bitstream_id" value
 * @method integer                             getBitstreamFormatId()                   Returns the current record's "bitstream_format_id" value
 * @method string                              getName()                                Returns the current record's "name" value
 * @method string                              getChecksum()                            Returns the current record's "checksum" value
 * @method string                              getChecksumAlgorithm()                   Returns the current record's "checksum_algorithm" value
 * @method string                              getDescription()                         Returns the current record's "description" value
 * @method string                              getUserFormatDescription()               Returns the current record's "user_format_description" value
 * @method string                              getSource()                              Returns the current record's "source" value
 * @method string                              getInternalId()                          Returns the current record's "internal_id" value
 * @method boolean                             getDeleted()                             Returns the current record's "deleted" value
 * @method integer                             getStoreNumber()                         Returns the current record's "store_number" value
 * @method integer                             getSequenceId()                          Returns the current record's "sequence_id" value
 * @method integer                             getSizeBytes()                           Returns the current record's "size_bytes" value
 * @method Public_Bitstreamformatregistry_Item getPublicBitstreamformatregistryItem()   Returns the current record's "Public_Bitstreamformatregistry_Item" value
 * @method Doctrine_Collection                 getPublicBundleItems()                   Returns the current record's "Public_Bundle_Items" collection
 * @method Doctrine_Collection                 getPublicMostRecentChecksumItems()       Returns the current record's "Public_MostRecentChecksum_Items" collection
 * @method Doctrine_Collection                 getPublicBundle2bitstreamItems()         Returns the current record's "Public_Bundle2bitstream_Items" collection
 * @method Doctrine_Collection                 getPublicCollectionItems()               Returns the current record's "Public_Collection_Items" collection
 * @method Doctrine_Collection                 getPublicCommunityItems()                Returns the current record's "Public_Community_Items" collection
 * @method Public_Bitstream_Item               setBitstreamId()                         Sets the current record's "bitstream_id" value
 * @method Public_Bitstream_Item               setBitstreamFormatId()                   Sets the current record's "bitstream_format_id" value
 * @method Public_Bitstream_Item               setName()                                Sets the current record's "name" value
 * @method Public_Bitstream_Item               setChecksum()                            Sets the current record's "checksum" value
 * @method Public_Bitstream_Item               setChecksumAlgorithm()                   Sets the current record's "checksum_algorithm" value
 * @method Public_Bitstream_Item               setDescription()                         Sets the current record's "description" value
 * @method Public_Bitstream_Item               setUserFormatDescription()               Sets the current record's "user_format_description" value
 * @method Public_Bitstream_Item               setSource()                              Sets the current record's "source" value
 * @method Public_Bitstream_Item               setInternalId()                          Sets the current record's "internal_id" value
 * @method Public_Bitstream_Item               setDeleted()                             Sets the current record's "deleted" value
 * @method Public_Bitstream_Item               setStoreNumber()                         Sets the current record's "store_number" value
 * @method Public_Bitstream_Item               setSequenceId()                          Sets the current record's "sequence_id" value
 * @method Public_Bitstream_Item               setSizeBytes()                           Sets the current record's "size_bytes" value
 * @method Public_Bitstream_Item               setPublicBitstreamformatregistryItem()   Sets the current record's "Public_Bitstreamformatregistry_Item" value
 * @method Public_Bitstream_Item               setPublicBundleItems()                   Sets the current record's "Public_Bundle_Items" collection
 * @method Public_Bitstream_Item               setPublicMostRecentChecksumItems()       Sets the current record's "Public_MostRecentChecksum_Items" collection
 * @method Public_Bitstream_Item               setPublicBundle2bitstreamItems()         Sets the current record's "Public_Bundle2bitstream_Items" collection
 * @method Public_Bitstream_Item               setPublicCollectionItems()               Sets the current record's "Public_Collection_Items" collection
 * @method Public_Bitstream_Item               setPublicCommunityItems()                Sets the current record's "Public_Community_Items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Bitstream_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bitstream');
        $this->hasColumn('bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('bitstream_format_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('checksum', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('checksum_algorithm', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_format_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('source', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('internal_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('deleted', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('store_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('sequence_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('size_bytes', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Bitstreamformatregistry_Item', array(
             'local' => 'bitstream_format_id',
             'foreign' => 'bitstream_format_id'));

        $this->hasMany('Public_Bundle_Item as Public_Bundle_Items', array(
             'local' => 'bitstream_id',
             'foreign' => 'primary_bitstream_id'));

        $this->hasMany('Public_MostRecentChecksum_Item as Public_MostRecentChecksum_Items', array(
             'local' => 'bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasMany('Public_Bundle2bitstream_Item as Public_Bundle2bitstream_Items', array(
             'local' => 'bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasMany('Public_Collection_Item as Public_Collection_Items', array(
             'local' => 'bitstream_id',
             'foreign' => 'logo_bitstream_id'));

        $this->hasMany('Public_Community_Item as Public_Community_Items', array(
             'local' => 'bitstream_id',
             'foreign' => 'logo_bitstream_id'));
    }
}