<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_CollectionItemCount_Item', 'doctrine');

/**
 * BasePublic_CollectionItemCount_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $collection_id
 * @property integer $count
 * @property Public_Collection_Item $Public_Collection_Item
 * 
 * @method integer                         getCollectionId()           Returns the current record's "collection_id" value
 * @method integer                         getCount()                  Returns the current record's "count" value
 * @method Public_Collection_Item          getPublicCollectionItem()   Returns the current record's "Public_Collection_Item" value
 * @method Public_CollectionItemCount_Item setCollectionId()           Sets the current record's "collection_id" value
 * @method Public_CollectionItemCount_Item setCount()                  Sets the current record's "count" value
 * @method Public_CollectionItemCount_Item setPublicCollectionItem()   Sets the current record's "Public_Collection_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_CollectionItemCount_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.collection_item_count');
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Collection_Item', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));
    }
}