<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CollectionItemCount', 'doctrine');

/**
 * BaseCollectionItemCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $collection_id
 * @property integer $count
 * @property Collection $Collection
 * 
 * @method integer             getCollectionId()  Returns the current record's "collection_id" value
 * @method integer             getCount()         Returns the current record's "count" value
 * @method Collection          getCollection()    Returns the current record's "Collection" value
 * @method CollectionItemCount setCollectionId()  Sets the current record's "collection_id" value
 * @method CollectionItemCount setCount()         Sets the current record's "count" value
 * @method CollectionItemCount setCollection()    Sets the current record's "Collection" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollectionItemCount extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.collection_item_count');
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Collection', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));
    }
}