<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Subscription_Item', 'doctrine');

/**
 * BasePublic_Subscription_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subscription_id
 * @property integer $eperson_id
 * @property integer $collection_id
 * @property Public_Eperson_Item $Public_Eperson_Item
 * @property Public_Collection_Item $Public_Collection_Item
 * 
 * @method integer                  getSubscriptionId()         Returns the current record's "subscription_id" value
 * @method integer                  getEpersonId()              Returns the current record's "eperson_id" value
 * @method integer                  getCollectionId()           Returns the current record's "collection_id" value
 * @method Public_Eperson_Item      getPublicEpersonItem()      Returns the current record's "Public_Eperson_Item" value
 * @method Public_Collection_Item   getPublicCollectionItem()   Returns the current record's "Public_Collection_Item" value
 * @method Public_Subscription_Item setSubscriptionId()         Sets the current record's "subscription_id" value
 * @method Public_Subscription_Item setEpersonId()              Sets the current record's "eperson_id" value
 * @method Public_Subscription_Item setCollectionId()           Sets the current record's "collection_id" value
 * @method Public_Subscription_Item setPublicEpersonItem()      Sets the current record's "Public_Eperson_Item" value
 * @method Public_Subscription_Item setPublicCollectionItem()   Sets the current record's "Public_Collection_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Subscription_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.subscription');
        $this->hasColumn('subscription_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eperson_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Eperson_Item', array(
             'local' => 'eperson_id',
             'foreign' => 'eperson_id'));

        $this->hasOne('Public_Collection_Item', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));
    }
}