<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tasklistitem', 'doctrine');

/**
 * BaseTasklistitem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tasklist_id
 * @property integer $eperson_id
 * @property integer $workflow_id
 * @property Eperson $Eperson
 * @property Workflowitem $Workflowitem
 * 
 * @method integer      getTasklistId()   Returns the current record's "tasklist_id" value
 * @method integer      getEpersonId()    Returns the current record's "eperson_id" value
 * @method integer      getWorkflowId()   Returns the current record's "workflow_id" value
 * @method Eperson      getEperson()      Returns the current record's "Eperson" value
 * @method Workflowitem getWorkflowitem() Returns the current record's "Workflowitem" value
 * @method Tasklistitem setTasklistId()   Sets the current record's "tasklist_id" value
 * @method Tasklistitem setEpersonId()    Sets the current record's "eperson_id" value
 * @method Tasklistitem setWorkflowId()   Sets the current record's "workflow_id" value
 * @method Tasklistitem setEperson()      Sets the current record's "Eperson" value
 * @method Tasklistitem setWorkflowitem() Sets the current record's "Workflowitem" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTasklistitem extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.tasklistitem');
        $this->hasColumn('tasklist_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eperson_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('workflow_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Eperson', array(
             'local' => 'eperson_id',
             'foreign' => 'eperson_id'));

        $this->hasOne('Workflowitem', array(
             'local' => 'workflow_id',
             'foreign' => 'workflow_id'));
    }
}