<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Community', 'doctrine');

/**
 * BaseCommunity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $community_id
 * @property string $name
 * @property string $short_description
 * @property string $introductory_text
 * @property integer $logo_bitstream_id
 * @property string $copyright_text
 * @property string $side_bar_text
 * @property integer $admin
 * @property Bitstream $Bitstream
 * @property Epersongroup $Epersongroup
 * @property Doctrine_Collection $Community2collections
 * @property Doctrine_Collection $Community2communitys_ForParentComm
 * @property Doctrine_Collection $Community2communitys_ForChildComm
 * @property Doctrine_Collection $CommunityItemCounts
 * @property Doctrine_Collection $Communities2items
 * 
 * @method integer             getCommunityId()                        Returns the current record's "community_id" value
 * @method string              getName()                               Returns the current record's "name" value
 * @method string              getShortDescription()                   Returns the current record's "short_description" value
 * @method string              getIntroductoryText()                   Returns the current record's "introductory_text" value
 * @method integer             getLogoBitstreamId()                    Returns the current record's "logo_bitstream_id" value
 * @method string              getCopyrightText()                      Returns the current record's "copyright_text" value
 * @method string              getSideBarText()                        Returns the current record's "side_bar_text" value
 * @method integer             getAdmin()                              Returns the current record's "admin" value
 * @method Bitstream           getBitstream()                          Returns the current record's "Bitstream" value
 * @method Epersongroup        getEpersongroup()                       Returns the current record's "Epersongroup" value
 * @method Doctrine_Collection getCommunity2collections()              Returns the current record's "Community2collections" collection
 * @method Doctrine_Collection getCommunity2communitysForParentComm()  Returns the current record's "Community2communitys_ForParentComm" collection
 * @method Doctrine_Collection getCommunity2communitysForChildComm()   Returns the current record's "Community2communitys_ForChildComm" collection
 * @method Doctrine_Collection getCommunityItemCounts()                Returns the current record's "CommunityItemCounts" collection
 * @method Doctrine_Collection getCommunities2items()                  Returns the current record's "Communities2items" collection
 * @method Community           setCommunityId()                        Sets the current record's "community_id" value
 * @method Community           setName()                               Sets the current record's "name" value
 * @method Community           setShortDescription()                   Sets the current record's "short_description" value
 * @method Community           setIntroductoryText()                   Sets the current record's "introductory_text" value
 * @method Community           setLogoBitstreamId()                    Sets the current record's "logo_bitstream_id" value
 * @method Community           setCopyrightText()                      Sets the current record's "copyright_text" value
 * @method Community           setSideBarText()                        Sets the current record's "side_bar_text" value
 * @method Community           setAdmin()                              Sets the current record's "admin" value
 * @method Community           setBitstream()                          Sets the current record's "Bitstream" value
 * @method Community           setEpersongroup()                       Sets the current record's "Epersongroup" value
 * @method Community           setCommunity2collections()              Sets the current record's "Community2collections" collection
 * @method Community           setCommunity2communitysForParentComm()  Sets the current record's "Community2communitys_ForParentComm" collection
 * @method Community           setCommunity2communitysForChildComm()   Sets the current record's "Community2communitys_ForChildComm" collection
 * @method Community           setCommunityItemCounts()                Sets the current record's "CommunityItemCounts" collection
 * @method Community           setCommunities2items()                  Sets the current record's "Communities2items" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCommunity extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.community');
        $this->hasColumn('community_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('short_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('introductory_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('logo_bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('copyright_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('side_bar_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('admin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bitstream', array(
             'local' => 'logo_bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasOne('Epersongroup', array(
             'local' => 'admin',
             'foreign' => 'eperson_group_id'));

        $this->hasMany('Community2collection as Community2collections', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));

        $this->hasMany('Community2community as Community2communitys_ForParentComm', array(
             'local' => 'community_id',
             'foreign' => 'parent_comm_id'));

        $this->hasMany('Community2community as Community2communitys_ForChildComm', array(
             'local' => 'community_id',
             'foreign' => 'child_comm_id'));

        $this->hasMany('CommunityItemCount as CommunityItemCounts', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));

        $this->hasMany('Communities2item as Communities2items', array(
             'local' => 'community_id',
             'foreign' => 'community_id'));
    }
}