<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Group2groupcache', 'doctrine');

/**
 * BaseGroup2groupcache
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property integer $child_id
 * @property Epersongroup $Epersongroup_ForChild
 * @property Epersongroup $Epersongroup_ForParent
 * 
 * @method integer          getId()                     Returns the current record's "id" value
 * @method integer          getParentId()               Returns the current record's "parent_id" value
 * @method integer          getChildId()                Returns the current record's "child_id" value
 * @method Epersongroup     getEpersongroupForChild()   Returns the current record's "Epersongroup_ForChild" value
 * @method Epersongroup     getEpersongroupForParent()  Returns the current record's "Epersongroup_ForParent" value
 * @method Group2groupcache setId()                     Sets the current record's "id" value
 * @method Group2groupcache setParentId()               Sets the current record's "parent_id" value
 * @method Group2groupcache setChildId()                Sets the current record's "child_id" value
 * @method Group2groupcache setEpersongroupForChild()   Sets the current record's "Epersongroup_ForChild" value
 * @method Group2groupcache setEpersongroupForParent()  Sets the current record's "Epersongroup_ForParent" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup2groupcache extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.group2groupcache');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('child_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Epersongroup as Epersongroup_ForChild', array(
             'local' => 'child_id',
             'foreign' => 'eperson_group_id'));

        $this->hasOne('Epersongroup as Epersongroup_ForParent', array(
             'local' => 'parent_id',
             'foreign' => 'eperson_group_id'));
    }
}