<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Bundle', 'doctrine');

/**
 * BaseBundle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bundle_id
 * @property string $name
 * @property integer $primary_bitstream_id
 * @property Bitstream $Bitstream
 * @property Doctrine_Collection $Bundle2bitstreams
 * @property Doctrine_Collection $Item2bundles
 * 
 * @method integer             getBundleId()             Returns the current record's "bundle_id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method integer             getPrimaryBitstreamId()   Returns the current record's "primary_bitstream_id" value
 * @method Bitstream           getBitstream()            Returns the current record's "Bitstream" value
 * @method Doctrine_Collection getBundle2bitstreams()    Returns the current record's "Bundle2bitstreams" collection
 * @method Doctrine_Collection getItem2bundles()         Returns the current record's "Item2bundles" collection
 * @method Bundle              setBundleId()             Sets the current record's "bundle_id" value
 * @method Bundle              setName()                 Sets the current record's "name" value
 * @method Bundle              setPrimaryBitstreamId()   Sets the current record's "primary_bitstream_id" value
 * @method Bundle              setBitstream()            Sets the current record's "Bitstream" value
 * @method Bundle              setBundle2bitstreams()    Sets the current record's "Bundle2bitstreams" collection
 * @method Bundle              setItem2bundles()         Sets the current record's "Item2bundles" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBundle extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bundle');
        $this->hasColumn('bundle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('primary_bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bitstream', array(
             'local' => 'primary_bitstream_id',
             'foreign' => 'bitstream_id'));

        $this->hasMany('Bundle2bitstream as Bundle2bitstreams', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));

        $this->hasMany('Item2bundle as Item2bundles', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));
    }
}