<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FileExtension', 'doctrine');

/**
 * BaseFileExtension
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_extension_id
 * @property integer $bitstream_format_id
 * @property string $extension
 * @property BitstreamFormatRegistry $Format
 * 
 * @method integer                 getFileExtensionId()     Returns the current record's "file_extension_id" value
 * @method integer                 getBitstreamFormatId()   Returns the current record's "bitstream_format_id" value
 * @method string                  getExtension()           Returns the current record's "extension" value
 * @method BitstreamFormatRegistry getFormat()              Returns the current record's "Format" value
 * @method FileExtension           setFileExtensionId()     Sets the current record's "file_extension_id" value
 * @method FileExtension           setBitstreamFormatId()   Sets the current record's "bitstream_format_id" value
 * @method FileExtension           setExtension()           Sets the current record's "extension" value
 * @method FileExtension           setFormat()              Sets the current record's "Format" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileExtension extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.fileextension');
        $this->hasColumn('file_extension_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('bitstream_format_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('extension', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BitstreamFormatRegistry as Format', array(
             'local' => 'bitstream_format_id',
             'foreign' => 'bitstream_format_id'));
    }
}