<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Item2bundle', 'doctrine');

/**
 * BaseItem2bundle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $item_id
 * @property integer $bundle_id
 * @property Item $Item
 * @property Bundle $Bundle
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getItemId()    Returns the current record's "item_id" value
 * @method integer     getBundleId()  Returns the current record's "bundle_id" value
 * @method Item        getItem()      Returns the current record's "Item" value
 * @method Bundle      getBundle()    Returns the current record's "Bundle" value
 * @method Item2bundle setId()        Sets the current record's "id" value
 * @method Item2bundle setItemId()    Sets the current record's "item_id" value
 * @method Item2bundle setBundleId()  Sets the current record's "bundle_id" value
 * @method Item2bundle setItem()      Sets the current record's "Item" value
 * @method Item2bundle setBundle()    Sets the current record's "Bundle" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem2bundle extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.item2bundle');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('bundle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));

        $this->hasOne('Bundle', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));
    }
}