<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ChecksumResults', 'doctrine');

/**
 * BaseChecksumResults
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $result_code
 * @property string $result_description
 * @property Doctrine_Collection $MostRecentChecksums
 * @property Doctrine_Collection $ChecksumHistorys
 * 
 * @method string              getResultCode()          Returns the current record's "result_code" value
 * @method string              getResultDescription()   Returns the current record's "result_description" value
 * @method Doctrine_Collection getMostRecentChecksums() Returns the current record's "MostRecentChecksums" collection
 * @method Doctrine_Collection getChecksumHistorys()    Returns the current record's "ChecksumHistorys" collection
 * @method ChecksumResults     setResultCode()          Sets the current record's "result_code" value
 * @method ChecksumResults     setResultDescription()   Sets the current record's "result_description" value
 * @method ChecksumResults     setMostRecentChecksums() Sets the current record's "MostRecentChecksums" collection
 * @method ChecksumResults     setChecksumHistorys()    Sets the current record's "ChecksumHistorys" collection
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChecksumResults extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.checksum_results');
        $this->hasColumn('result_code', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('result_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MostRecentChecksum as MostRecentChecksums', array(
             'local' => 'result_code',
             'foreign' => 'result'));

        $this->hasMany('ChecksumHistory as ChecksumHistorys', array(
             'local' => 'result_code',
             'foreign' => 'result'));
    }
}