<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_ChecksumHistory_Item', 'doctrine');

/**
 * BasePublic_ChecksumHistory_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $check_id
 * @property integer $bitstream_id
 * @property timestamp $process_start_date
 * @property timestamp $process_end_date
 * @property string $checksum_expected
 * @property string $checksum_calculated
 * @property string $result
 * @property Public_ChecksumResults_Item $Public_ChecksumResults_Item
 * 
 * @method integer                     getCheckId()                     Returns the current record's "check_id" value
 * @method integer                     getBitstreamId()                 Returns the current record's "bitstream_id" value
 * @method timestamp                   getProcessStartDate()            Returns the current record's "process_start_date" value
 * @method timestamp                   getProcessEndDate()              Returns the current record's "process_end_date" value
 * @method string                      getChecksumExpected()            Returns the current record's "checksum_expected" value
 * @method string                      getChecksumCalculated()          Returns the current record's "checksum_calculated" value
 * @method string                      getResult()                      Returns the current record's "result" value
 * @method Public_ChecksumResults_Item getPublicChecksumResultsItem()   Returns the current record's "Public_ChecksumResults_Item" value
 * @method Public_ChecksumHistory_Item setCheckId()                     Sets the current record's "check_id" value
 * @method Public_ChecksumHistory_Item setBitstreamId()                 Sets the current record's "bitstream_id" value
 * @method Public_ChecksumHistory_Item setProcessStartDate()            Sets the current record's "process_start_date" value
 * @method Public_ChecksumHistory_Item setProcessEndDate()              Sets the current record's "process_end_date" value
 * @method Public_ChecksumHistory_Item setChecksumExpected()            Sets the current record's "checksum_expected" value
 * @method Public_ChecksumHistory_Item setChecksumCalculated()          Sets the current record's "checksum_calculated" value
 * @method Public_ChecksumHistory_Item setResult()                      Sets the current record's "result" value
 * @method Public_ChecksumHistory_Item setPublicChecksumResultsItem()   Sets the current record's "Public_ChecksumResults_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_ChecksumHistory_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.checksum_history');
        $this->hasColumn('check_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'public.checksum_history_check_id',
             'length' => 8,
             ));
        $this->hasColumn('bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('process_start_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('process_end_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('checksum_expected', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('checksum_calculated', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('result', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_ChecksumResults_Item', array(
             'local' => 'result',
             'foreign' => 'result_code'));
    }
}