<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Collection2item_Item', 'doctrine');

/**
 * BasePublic_Collection2item_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $collection_id
 * @property integer $item_id
 * @property Public_Collection_Item $Public_Collection_Item
 * @property Public_Item_Item $Public_Item_Item_ForItem
 * 
 * @method integer                     getId()                       Returns the current record's "id" value
 * @method integer                     getCollectionId()             Returns the current record's "collection_id" value
 * @method integer                     getItemId()                   Returns the current record's "item_id" value
 * @method Public_Collection_Item      getPublicCollectionItem()     Returns the current record's "Public_Collection_Item" value
 * @method Public_Item_Item            getPublicItemItemForItem()    Returns the current record's "Public_Item_Item_ForItem" value
 * @method Public_Collection2item_Item setId()                       Sets the current record's "id" value
 * @method Public_Collection2item_Item setCollectionId()             Sets the current record's "collection_id" value
 * @method Public_Collection2item_Item setItemId()                   Sets the current record's "item_id" value
 * @method Public_Collection2item_Item setPublicCollectionItem()     Sets the current record's "Public_Collection_Item" value
 * @method Public_Collection2item_Item setPublicItemItemForItem()    Sets the current record's "Public_Item_Item_ForItem" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Collection2item_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.collection2item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('collection_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Collection_Item', array(
             'local' => 'collection_id',
             'foreign' => 'collection_id'));

        $this->hasOne('Public_Item_Item as Public_Item_Item_ForItem', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));
    }
}