<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Bi2Dmap', 'doctrine');

/**
 * BaseBi2Dmap
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $map_id
 * @property integer $item_id
 * @property integer $distinct_id
 * @property Bi2Dis $Bi2Dis
 * @property Item $Item
 * 
 * @method integer getMapId()       Returns the current record's "map_id" value
 * @method integer getItemId()      Returns the current record's "item_id" value
 * @method integer getDistinctId()  Returns the current record's "distinct_id" value
 * @method Bi2Dis  getBi2Dis()      Returns the current record's "Bi2Dis" value
 * @method Item    getItem()        Returns the current record's "Item" value
 * @method Bi2Dmap setMapId()       Sets the current record's "map_id" value
 * @method Bi2Dmap setItemId()      Sets the current record's "item_id" value
 * @method Bi2Dmap setDistinctId()  Sets the current record's "distinct_id" value
 * @method Bi2Dmap setBi2Dis()      Sets the current record's "Bi2Dis" value
 * @method Bi2Dmap setItem()        Sets the current record's "Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBi2Dmap extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bi_2_dmap');
        $this->hasColumn('map_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('distinct_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bi2Dis', array(
             'local' => 'distinct_id',
             'foreign' => 'distinct_id'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'item_id'));
    }
}