<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Public_Bundle2bitstream_Item', 'doctrine');

/**
 * BasePublic_Bundle2bitstream_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bundle_id
 * @property integer $bitstream_id
 * @property Public_Bundle_Item $Public_Bundle_Item
 * @property Public_Bitstream_Item $Public_Bitstream_Item
 * 
 * @method integer                      getId()                    Returns the current record's "id" value
 * @method integer                      getBundleId()              Returns the current record's "bundle_id" value
 * @method integer                      getBitstreamId()           Returns the current record's "bitstream_id" value
 * @method Public_Bundle_Item           getPublicBundleItem()      Returns the current record's "Public_Bundle_Item" value
 * @method Public_Bitstream_Item        getPublicBitstreamItem()   Returns the current record's "Public_Bitstream_Item" value
 * @method Public_Bundle2bitstream_Item setId()                    Sets the current record's "id" value
 * @method Public_Bundle2bitstream_Item setBundleId()              Sets the current record's "bundle_id" value
 * @method Public_Bundle2bitstream_Item setBitstreamId()           Sets the current record's "bitstream_id" value
 * @method Public_Bundle2bitstream_Item setPublicBundleItem()      Sets the current record's "Public_Bundle_Item" value
 * @method Public_Bundle2bitstream_Item setPublicBitstreamItem()   Sets the current record's "Public_Bitstream_Item" value
 * 
 * @package    dspace
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublic_Bundle2bitstream_Item extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public.bundle2bitstream');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('bundle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('bitstream_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Public_Bundle_Item', array(
             'local' => 'bundle_id',
             'foreign' => 'bundle_id'));

        $this->hasOne('Public_Bitstream_Item', array(
             'local' => 'bitstream_id',
             'foreign' => 'bitstream_id'));
    }
}